name: spotis

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        image: maya-florenko/spotis
        container_name: spotis
        restart: unless-stopped
        environment:
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
