name: spotis

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        image: maya-florenko/spotis
        container_name: spotis
        restart: unless-stopped
        environment:
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
            - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
            - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
            - DEEZER_ARL=${DEEZER_ARL}
            - DEEZER_SECRET=${DEEZER_SECRET}
